### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by leoj3n** [seletskiy/secrets#1]
Why is this a public repo? Are there files that I can't see and if so how?

**Comment by leoj3n** [comment]
https://github.com/seletskiy/carcosa ?

**Comment by kovetskiy** [comment]
@leoj3n yes, it's carcosa

**Comment by leoj3n** [comment]
Not clear to me what kind of information can be stored and how it is stored? I get that it's encrypted into git somehow.

**Comment by seletskiy** [comment]
@leoj3n: Yes, it's carcosa. It uses AES under the hood and information of any kind can be stored. Encrypted data requires master password to be decrypted back. If you have further questions I suggest to move into carcosa repo for the further discussion.

**Comment by leoj3n** [comment]
Thank you.
